name: summerbreeze
recipe: drupal9
config:
  php: '8.2'
  webroot: web

# Services
services:
  database:
    portforward: 52981
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
  summerbreeze-phpmyadmin:
    type: phpmyadmin

# Proxy
proxy:
  summerbreeze-phpmyadmin:
    - summerbreeze-phpmyadmin.lndo.site
